################################################################################
MLI_FILE		= cordova_geolocation.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-geolocation
################################################################################
